# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-21 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0002_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cleaners.Cities'),
            preserve_default=False,
        ),
    ]
